#!/usr/bin/env python
"""
Generate the Connect IQ launcher icons.

Garmin sizes the launcher icon per device, so each panel family gets its own
resources-round-<W>x<H>/drawables/launcher_icon.png at that family's size. The
SDK's built-in device-family qualifiers put those folders on the resource path
automatically, so monkey.jungle needs no rules for them.

Run:  python tools/gen_icons.py
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from goatart import render, MEADOW  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# (icon size, resource folder). The base set is the fallback for any panel that
# somehow has no family folder of its own.
TARGETS = [
    (65, "resources"),
    (70, "resources-round-454x454"),
    (70, "resources-round-416x416"),
    (70, "resources-round-390x390"),
    (61, "resources-round-360x360"),
    (40, "resources-round-280x280"),
    (40, "resources-round-260x260"),
    (40, "resources-round-240x240"),
    (40, "resources-round-218x218"),
]

DRAWABLES_XML = (
    '<resources>\n'
    '    <!-- Launcher icon, generated by tools/gen_icons.py at this panel\'s size. -->\n'
    '    <bitmap id="LauncherIcon" filename="launcher_icon.png" />\n'
    '</resources>\n'
)


def main():
    for size, reldir in TARGETS:
        outdir = os.path.join(ROOT, reldir, "drawables")
        os.makedirs(outdir, exist_ok=True)
        icon = render(size, bg=MEADOW, scale=0.86)
        icon.save(os.path.join(outdir, "launcher_icon.png"))
        with open(os.path.join(outdir, "drawables.xml"), "w", newline="\n") as f:
            f.write(DRAWABLES_XML)
        print("%-28s %dx%d" % (reldir, size, size))
    print("Done.")


if __name__ == "__main__":
    main()
